// import Colors from '../constants/Colors';

import Colors from '../constants/Colors';
import Fonts from '../constants/Fonts';

const React = require('react-native');

export default {
  headerContainer: {
    flexDirection: 'row',
    padding: 17,
    //paddingTop:45,
    backgroundColor: 'green',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'relative',
    width: '100%',
  },
  inputField: {
    marginTop: 15,
    marginBottom: 5,
  },
  loginBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#A5DE18',
    marginVertical: 10,
    borderRadius: 5,
  },
  btnTxt2: {
    textAlign: 'center',
    paddingRight: 7,
    color: 'black',
    // fontWeight: '700',
    fontFamily: Fonts.bold,
  },
  text2: {
    textAlign: 'center',
    fontFamily: Fonts.bold,
    marginTop: 40,
    fontSize: 12,
    color: 'black',
  },
  button: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 10,
    elevation: 5,
    marginVertical: 10,
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 10,
    borderWidth: 1,
    borderColor: 'grey',
  },
  lgnbtnTxt: {
    fontFamily: 'BlissPro-Bold',
    marginLeft: 12,
    textAlign: 'center',
    color: 'black',
  },
  titleText: {
    fontSize: 20,
    marginLeft: 'auto',
    marginRight: 'auto',
    color: '#fff',
    fontFamily: 'BlissPro-Bold',
  },
  confirmModalContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,.8)',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  confirmModalContent: {
    backgroundColor: '#fff',
    width: '85%',
    borderRadius: 8,
    padding: 25,
  },
  confirmButTxt: {
    // color: Colors.cfmIconColor,
    fontFamily: 'BlissPro-Bold',
    fontSize: 18,
    marginLeft: 15,
  },
  confirmfmText: {
    fontSize: 17,
    fontFamily: 'BlissPro-Bold',
    color: 'black',

    textAlign: 'center',
    marginTop: 5,
  },
  warnfmText: {
    fontSize: 17,
    fontFamily: 'BlissPro-Bold',
    color: 'black',
    fontWeight: 'normal',
    textAlign: 'center',
  },
  nearBy: {
    display: 'flex',
    textAlign: 'center',
    fontWeight: 'normal',
    color: 'black',
    fontSize: 15,
    fontFamily: 'BlissPro-Bold',
  },
  distanceClick: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 10,
    elevation: 3,
    marginLeft: 5,
    marginRight: 5,
  },
  filterCont: {
    backgroundColor: '#EBF4FA',
    borderRadius: 8,
    justifyContent: 'center',
    padding: 10,
    margin: 20,
    elevation: 5,
    overflow: 'hidden',
    // borderWidth: 0.4,
  },
  filterTxt: {
    marginLeft: 5,
    fontFamily: 'BlissPro-Bold',
    fontSize: 20,
    color: 'blue',
    // fontWeight: '700',
  },
  networkModalContent: {
    backgroundColor: '#fff',
    width: '85%',
    borderRadius: 8,
    padding: 25,
  },
  networkErrorText: {
    fontSize: 16,
    fontFamily: Fonts.regular,
    color: Colors.primaryDarkGreen,
  },
  tryAgainBtn: {
    alignSelf: 'flex-end',
    marginTop: 10,
  },
  modalContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  tryAgainTxt: {
    color: Colors.primaryDarkGreen,
    fontFamily: Fonts.bold,
    fontSize: 18,
    marginRight: 15,
  },
};
